[package]
name = "uri-template"
version = "0.1.0"
edition = "2018"

[dependencies]

[dev-dependencies]
indexmap = {version = "1", features = ["serde"]}
serde = {version = "1", features = ["derive"]}
serde_json = {version = "1", features = ["indexmap"]}
